twig:
    default_path: '%kernel.project_dir%/templates'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        uploads_dir_name: 'assets/content/uploads'
        uploads_base_url: '%env(SITE_BASE_URL)%/%uploads_dir_name%'

when@test:
    twig:
        strict_variables: true
