
framework:
    validation:
        email_validation_mode: html5

        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []

App\Entity\User:
    properties:
        username:
            - UniqueEntity: { groups: [registration] }

App\Entity\Service:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [host, port]
            errorPath: port
            message: 'This port is already in use on that host.'